// Test IDs for the daily cash-closing (Cierre de caja) feature.
export const ACCOUNTING = {
        panel: 'accounting-panel',
        datePicker: 'accounting-date-picker',
        refreshBtn: 'accounting-refresh-btn',
        seedBtn: 'accounting-seed-btn',
        saldoInicial: 'accounting-saldo-inicial',
        totalEntradas: 'accounting-total-entradas',
        totalSalidas: 'accounting-total-salidas',
        saldoFinal: 'accounting-saldo-final',
        downloadCsv: 'accounting-download-csv',
        downloadPdf: 'accounting-download-pdf',
        movementsTable: 'accounting-movements-table',
        openingInput: 'accounting-opening-input',
        openingSaveBtn: 'accounting-opening-save-btn',
        movConcept: 'accounting-mov-concept',
        movAmount: 'accounting-mov-amount',
        movType: 'accounting-mov-type',
        movMethod: 'accounting-mov-method',
        movAddBtn: 'accounting-mov-add-btn',
        efectivoEsperado: 'accounting-efectivo-esperado',
        cashCountSection: 'accounting-cash-count-section',
        cashCountQty: 'accounting-cash-count-qty',
        cashCountTotal: 'accounting-cash-count-total',
        cashCountSaveBtn: 'accounting-cash-count-save-btn',
        cashCountClearBtn: 'accounting-cash-count-clear-btn',
        reconciliationBanner: 'accounting-reconciliation-banner',
        reconciliationDiff: 'accounting-reconciliation-diff',
        historySection: 'accounting-history-section',
        historyTable: 'accounting-history-table',
        historyRow: 'accounting-history-row',
        historyViewBtn: 'accounting-history-view-btn',
};
